# !/bin/bash

java -jar lostword.jar 2.conf &&
java -jar lostword.jar 3.conf &&
java -jar lostword.jar 4.conf &&
java -jar lostword.jar 5.conf &&
java -jar lostword.jar 6.conf &&
java -jar lostword.jar 7.conf &&
java -jar lostword.jar 8.conf &&
java -jar lostword.jar 9.conf &&
java -jar lostword.jar 10.conf &&
java -jar lostword.jar 11.conf &&
java -jar lostword.jar 12.conf &&
java -jar lostword.jar 13.conf &&
java -jar lostword.jar 14.conf &&
java -jar lostword.jar 15.conf &&
java -jar lostword.jar 16.conf &&
java -jar lostword.jar 17.conf &&
java -jar lostword.jar 18.conf &&
java -jar lostword.jar 19.conf &&
java -jar lostword.jar 20.conf &&
java -jar lostword.jar 21.conf &&
java -jar lostword.jar 22.conf &&
java -jar lostword.jar 23.conf &&
java -jar lostword.jar 24.conf &&
java -jar lostword.jar 25.conf &&
java -jar lostword.jar 26.conf &&
java -jar lostword.jar 27.conf &&
java -jar lostword.jar 28.conf &&
java -jar lostword.jar 29.conf &&
java -jar lostword.jar 30.conf &&
java -jar lostword.jar 31.conf &&
java -jar lostword.jar 32.conf &&
java -jar lostword.jar 33.conf &&
java -jar lostword.jar 34.conf &&
java -jar lostword.jar 35.conf &&
java -jar lostword.jar 36.conf &&
java -jar lostword.jar 37.conf &&
java -jar lostword.jar 38.conf &&
java -jar lostword.jar 39.conf &&
java -jar lostword.jar 40.conf &&
java -jar lostword.jar 41.conf &&
java -jar lostword.jar 42.conf &&
java -jar lostword.jar 43.conf &&
java -jar lostword.jar 44.conf &&
java -jar lostword.jar 45.conf &&
java -jar lostword.jar 46.conf &&
java -jar lostword.jar 47.conf &&
java -jar lostword.jar 48.conf &&
java -jar lostword.jar 49.conf &&
java -jar lostword.jar 50.conf &&
java -jar lostword.jar 51.conf &&
java -jar lostword.jar 52.conf &&
java -jar lostword.jar 53.conf &&
java -jar lostword.jar 54.conf &&
java -jar lostword.jar 55.conf &&
java -jar lostword.jar 56.conf &&
java -jar lostword.jar 57.conf &&
java -jar lostword.jar 58.conf &&
java -jar lostword.jar 59.conf &&
java -jar lostword.jar 60.conf &&
java -jar lostword.jar 61.conf &&
java -jar lostword.jar 62.conf &&
java -jar lostword.jar 63.conf &&
java -jar lostword.jar 64.conf &&
java -jar lostword.jar 65.conf &&
java -jar lostword.jar 66.conf &&
java -jar lostword.jar 67.conf &&
java -jar lostword.jar 68.conf &&
java -jar lostword.jar 69.conf &&
java -jar lostword.jar 70.conf